#!/bin/bash

#===========================================================#
# The purpose of this script is to get the picture of the day
# from bonjourmadame.com and to print it with the library.
#
# Used for a debug, or to cause an eye fracture.
#===========================================================#

tmpDir=/tmp/printer
tmpFile=$tmpDir/tmp
pic=$tmpDir/picture
output=$tmpDir/output.jpg

mkdir $tmpDir

wget http://www.bonjourmadame.fr/ -O $tmpFile

wget $(cat $tmpFile | grep -o "http://[0-9]\{2\}.media.tumblr.com/[a-z0-9]*/tumblr_[_a-zA-Z0-9]*.\(jpg\|png\)" | head -n 1) -O $pic

wid=$(identify $pic | cut -d ' ' -f3 | cut -d 'x' -f1)
hei=$(identify $pic | cut -d ' ' -f3 | cut -d 'x' -f2)
if [ $wid -gt $hei ]
then
    convert $pic -rotate 90 $tmpDir/.pictmp
    convert $tmpDir/.pictmp -resize 384x -normalize -auto-level -level 5%,80%,1.3 -dither FloydSteinberg -gamma 1.3 -colors 2 -colorspace gray -normalize $output
    rm $tmpDir/.pictmp
else
    convert $pic -resize 384x -normalize -auto-level -level 5%,80%,1.3 -dither FloydSteinberg -gamma 1.3 -colors 2 -colorspace gray -normalize $output
fi

$HOME/Projects/Multi/Printer/python/thermalPrinter.py -ocfb "$output"

rm -r $tmpDir
